# code: language=ansible
# vim: set filetype=yaml.ansible :
---
- name: Install sing-box
  tags:
    - sing-box-install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Configure sing-box
  tags:
    - sing-box-install
    - sing-box-configure
  ansible.builtin.import_tasks:
    file: configure.yml
