# code: language=ansible
# vim: set filetype=yaml.ansible :
---
- name: Converge
  hosts: all
  tasks:
    - name: set sample sing-box config
      ansible.builtin.set_fact:
        sing_box_config: |
          {
            "log": {
              "level": "info",
              "output": "stdout"
            },
            "inbounds": [
              {
                "type": "socks",
                "listen": "0.0.0.0",
                "listen_port": 1080,
                "users": [
                  {
                    "username": "myuser",
                    "password": "mypassword"
                  }
                ]
              }
            ],
            "outbounds": [
              {
                "type": "direct",
                "tag": "direct"
              }
            ]
          }

    - name: "include sing-box role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'GITHUB_WORKSPACE') }}"
